# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SoldierClient.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SoldierClient.proto\x12\rsoldierclient\"G\n\x19MissileApproachingRequest\x12\x14\n\x0cx_coordinate\x18\x01 \x01(\x05\x12\x14\n\x0cy_coordinate\x18\x02 \x01(\x05\"E\n\x17MissileApproachingReply\x12\x14\n\x0cx_coordinate\x18\x01 \x01(\x05\x12\x14\n\x0cy_coordinate\x18\x02 \x01(\x05\"&\n\x13SoldierReadyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t2\xda\x01\n\rSoldierClient\x12^\n\x0cSoldierReady\x12\".soldierclient.SoldierReadyRequest\x1a&.soldierclient.MissileApproachingReply\"\x00\x30\x01\x12i\n\x13missile_approaching\x12(.soldierclient.MissileApproachingRequest\x1a&.soldierclient.MissileApproachingReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SoldierClient_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_MISSILEAPPROACHINGREQUEST']._serialized_start=38
  _globals['_MISSILEAPPROACHINGREQUEST']._serialized_end=109
  _globals['_MISSILEAPPROACHINGREPLY']._serialized_start=111
  _globals['_MISSILEAPPROACHINGREPLY']._serialized_end=180
  _globals['_SOLDIERREADYREQUEST']._serialized_start=182
  _globals['_SOLDIERREADYREQUEST']._serialized_end=220
  _globals['_SOLDIERCLIENT']._serialized_start=223
  _globals['_SOLDIERCLIENT']._serialized_end=441
# @@protoc_insertion_point(module_scope)
