# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SoldierClient_pb2 as SoldierClient__pb2


class SoldierClientStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SoldierReady = channel.unary_stream(
                '/soldierclient.SoldierClient/SoldierReady',
                request_serializer=SoldierClient__pb2.SoldierReadyRequest.SerializeToString,
                response_deserializer=SoldierClient__pb2.MissileApproachingReply.FromString,
                )
        self.missile_approaching = channel.unary_unary(
                '/soldierclient.SoldierClient/missile_approaching',
                request_serializer=SoldierClient__pb2.MissileApproachingRequest.SerializeToString,
                response_deserializer=SoldierClient__pb2.MissileApproachingReply.FromString,
                )


class SoldierClientServicer(object):
    """The greeting service definition.
    """

    def SoldierReady(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def missile_approaching(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoldierClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SoldierReady': grpc.unary_stream_rpc_method_handler(
                    servicer.SoldierReady,
                    request_deserializer=SoldierClient__pb2.SoldierReadyRequest.FromString,
                    response_serializer=SoldierClient__pb2.MissileApproachingReply.SerializeToString,
            ),
            'missile_approaching': grpc.unary_unary_rpc_method_handler(
                    servicer.missile_approaching,
                    request_deserializer=SoldierClient__pb2.MissileApproachingRequest.FromString,
                    response_serializer=SoldierClient__pb2.MissileApproachingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'soldierclient.SoldierClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SoldierClient(object):
    """The greeting service definition.
    """

    @staticmethod
    def SoldierReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/soldierclient.SoldierClient/SoldierReady',
            SoldierClient__pb2.SoldierReadyRequest.SerializeToString,
            SoldierClient__pb2.MissileApproachingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def missile_approaching(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/soldierclient.SoldierClient/missile_approaching',
            SoldierClient__pb2.MissileApproachingRequest.SerializeToString,
            SoldierClient__pb2.MissileApproachingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
